# 静态文件存储绝对路径，配合nginx使用
xml_abspath: ""
torrent_abspath: ""
# 本地汇总rss文件名
total_xml_filename: total.xml
# 本地汇总rss保留项目数
max_items: 200
## 启用简繁转换
#cht_to_chs: 0

sites:
  dmhy:
    enable: 1
    rss_url: https://share.dmhy.org/topics/list/sort_id/2
    local_xml: dmhy.xml
    refresh_interval: 6
    save_torrent: 0

  acgrip:
    enable: 0
    rss_url: https://acg.rip/.xml
    local_xml: acgrip.xml
    refresh_interval: 6
    save_torrent: 1

  bangumimoe:
    enable: 0
    rss_url: https://bangumi.moe/rss/latest
    local_xml: bangumimoe.xml
    refresh_interval: 6
    save_torrent: 1

  acgnx:
    enable: 1
    rss_url: https://share.acgnx.se/rss-sort-1.xml
    local_xml: acgnx.xml
    refresh_interval: 6
    save_torrent: 0

  kisssub:
    enable: 1
    rss_url: http://www.kisssub.org/rss-1.xml
    local_xml: kisssub.xml
    refresh_interval: 6
    save_torrent: 0

  ncraw:
    enable: 1
    rss_url: https://ouo.si/feed?
    local_xml: ncraw.xml
    refresh_interval: 6
    save_torrent: 0

  mikan:
    enable: 0
    rss_url: https://mikanani.me/RSS/MyBangumi?token=XXXXXX
    local_xml: mikan.xml
    refresh_interval: 10
    save_torrent: 0

  nyaa:
    enable: 0
    rss_url: https://nyaa.si/?page=rss&c=1_3
    local_xml: nyaa.xml
    refresh_interval: 10
    save_torrent: 0


trackers:
  - https://tracker.mlsub.net:443/announce
  - https://trackers.mlsub.net:443/announce
  - https://opentracker.i2p.rocks:443/announce
  - http://tracker1.itzmx.com:8080/announce
  - http://share.camoe.cn:8080/announce
  - http://t.nyaatracker.com/announce
  - https://tr.ready4.icu/announce
  - http://nyaa.tracker.wf:7777/announce
  - http://open.acgnxtracker.com/announce
  - http://open.acgtracker.com:1096/announce

# internal config
useragent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"
max_retry: 3
wait_sec: 10