# xml文件存储绝对路径，配合nginx使用
#xml_abspath: /var/www/html/
xml_abspath: test_xml_path
# 聚合rss文件名
total_xml_filename: rss.xml
# 本地汇总rss保留项目数
max_items: 200

sites:
  #  example:
  #    # 是否启用本站点, 0或1
  #    enable: 0
  #    # rss链接, 可在目标站点选择具体分类再生成rss
  #    rss_url: https://example.com/rss.xml
  #    # 单个站点rss文件, 各任务rss名称不可相同
  #    local_xml_file: example.xml
  #    # 刷新间隔(min), 建议高于5min
  #    refresh_interval: 10

  dmhy:
    enable: 1
    rss_url: https://share.dmhy.org/topics/rss/sort_id/2/rss.xml
    local_xml_file: dmhy.xml
    refresh_interval: 6

  acgnx:
    enable: 1
    rss_url: https://share.acgnx.se/rss-sort-1.xml
    local_xml_file: acgnx.xml
    refresh_interval: 6

  kisssub:
    enable: 1
    rss_url: http://www.kisssub.org/rss-1.xml
    local_xml_file: kisssub.xml
    refresh_interval: 6

  ncraw:
    enable: 1
    rss_url: https://ouo.si/feed?
    local_xml_file: ncraw.xml
    refresh_interval: 6

  mikan:
    enable: 1
    rss_url: https://mikanani.me/RSS/MyBangumi?token=XXXXXXXXXX
    local_xml_file: mikan.xml
    refresh_interval: 10

  nyaa:
    enable: 1
    rss_url: https://nyaa.si/?page=rss&c=1_3
    local_xml_file: nyaa.xml
    # nyaa rss 刷新间隔必须足够长, 频繁刷新触发IP封禁
    refresh_interval: 10

  acgrip:
    # acgrip rss不提供magnet
    # 需全部缓存torrent逐个转换成magnet, 性能不佳
    enable: 0
    rss_url: https://acg.rip/.xml
    local_xml_file: acgrip.xml
    refresh_interval: 10

  bangumimoe:
    # bangumimoe rss不提供magnet
    # 需全部缓存torrent逐个转换成magnet, 性能不佳
    enable: 0
    rss_url: https://bangumi.moe/rss/latest
    local_xml_file: bangumimoe.xml
    refresh_interval: 6


add_trackers_to_magnet: 1
trackers:
  - https://tracker.mlsub.net:443/announce
  - https://trackers.mlsub.net:443/announce
  - https://opentracker.i2p.rocks:443/announce
  - http://tracker1.itzmx.com:8080/announce
  - http://share.camoe.cn:8080/announce
  - http://t.nyaatracker.com/announce
  - https://tr.ready4.icu/announce
  - http://nyaa.tracker.wf:7777/announce
  - http://open.acgnxtracker.com/announce
  - http://open.acgtracker.com:1096/announce

# 其他设定
useragent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"
max_retry: 3
fetch_wait_sec: 10
download_wait_sec: 3
